<?php

namespace Intelipost;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-28 at 10:33:58.
 */
class IntelipostProxyTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IntelipostProxy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IntelipostProxy;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Intelipost\IntelipostProxy::ConsultarMetodosDeEnvio
     * @todo   Implement testConsultarMetodosDeEnvio().
     */
    public function testConsultarMetodosDeEnvio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intelipost\IntelipostProxy::ConsultarCotacao
     * @todo   Implement testConsultarCotacao().
     */
    public function testConsultarCotacao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intelipost\IntelipostProxy::CotarSemVolumes
     * @todo   Implement testCotarSemVolumes().
     */
    public function testCotarSemVolumes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intelipost\IntelipostProxy::MarcarPedidoParaProntoParaEnvio
     * @todo   Implement testMarcarPedidoParaProntoParaEnvio().
     */
    public function testMarcarPedidoParaProntoParaEnvio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intelipost\IntelipostProxy::MarcarPedidoParaEnviado
     * @todo   Implement testMarcarPedidoParaEnviado().
     */
    public function testMarcarPedidoParaEnviado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intelipost\IntelipostProxy::CancelarPedidoEnviado
     * @todo   Implement testCancelarPedidoEnviado().
     */
    public function testCancelarPedidoEnviado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intelipost\IntelipostProxy::ConsultarPedidoEnviado
     * @todo   Implement testConsultarPedidoEnviado().
     */
    public function testConsultarPedidoEnviado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intelipost\IntelipostProxy::EnviarPedido
     * @todo   Implement testEnviarPedido().
     */
    public function testEnviarPedido() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
